INSERT INTO OFFICE
    (ID, ADDRESS)
VALUES (1, 'Office A');

INSERT INTO OFFICE
    (ID, ADDRESS)
VALUES (2, 'Office B');

INSERT INTO EMPLOYEE
    (ID, NAME, OFFICE_ID)
VALUES (1, 'Brian', 1);

INSERT INTO EMPLOYEE
    (ID, NAME, OFFICE_ID)
VALUES (2, 'Alice', 1);

INSERT INTO EMPLOYEE
    (ID, NAME, OFFICE_ID)
VALUES (3, 'John', 2);

INSERT INTO EMPLOYEE
    (ID, NAME, OFFICE_ID)
VALUES (4, 'Emma', 2);