CREATE TABLE OFFICE
(
    ID      BIGINT NOT NULL,
    ADDRESS VARCHAR(255),
    CONSTRAINT PK_OFFICE PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEE
(
    ID        BIGINT NOT NULL,
    NAME      VARCHAR(255),
    OFFICE_ID BIGINT,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID),
    CONSTRAINT FK_EMPLOYEE_OFFICE FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE (ID)
);
