CREATE TABLE OFFICE
(
    ID      BIGINT NOT NULL,
    ADDRESS VARCHAR(255),
    CONSTRAINT PK_OFFICE PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEE
(
    ID        BIGINT NOT NULL,
    NAME      VARCHAR(255),
    OFFICE_ID BIGINT,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID),
    CONSTRAINT FK_EMPLOYEE_OFFICE FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE (ID)
);

CREATE VIEW EMPLOYEE_OFFICE_VIEW AS
SELECT O.ID AS ID_OFFICE, O.ADDRESS AS ADDRESS_OFFICE, E.ID AS ID_EMPLOYEE, E.NAME AS NAME_EMPLOYEE
FROM OFFICE O
         INNER JOIN EMPLOYEE E ON O.ID = E.OFFICE_ID;